getbox:
  base-url: https://<GETBOX_BASE>
  api-key: ${GETBOX_API_KEY}
optiondepth:
  base-url: https://<OPTION_DEPTH_BASE>
  api-key: ${OPTION_DEPTH_API_KEY}

spring:
  datasource:
    url: jdbc:sqlite:./depthpulse.db       # crea un archivo en la raíz del proyecto
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update                     # crea tablas si no existen
  sql:
    initialization:
      mode: never                          # evita que Boot busque schema.sql
