getbox:
  base-url: https://api.gexbot.com
  api-key: demo-getbox-key

optiondepth:
  base-url: https://httpbin.org
  api-key: demo-optiondepth-key

spring:
  datasource:
    url: jdbc:sqlite:./depthpulse.db       # crea un archivo en la raíz del proyecto
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: create                     # crea tablas si no existen
  sql:
    initialization:
      mode: never                          # evita que Boot busque schema.sql
