package com.depthpulse.dto;

/**
 * Simple DTO that aggregates the raw responses from both API clients along
 * with a synthesized conclusion generated by the {@link
 * com.depthpulse.service.AnalysisService}.
 */
public record AnalysisPayload(String consulta,
                              String getboxJson,
                              String optionDepthJson,
                              String analysisSummary) {}
